github.com:
    oauth_token: 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
    user: hongcn5
    git_protocol: https
    users:
        hongcn5:
            oauth_token: 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
